### ISSUE TITLE
how to compile

### ISSUE THREAD

**Issue by qlwz** [diyruz/freepad#15]
Z-Stack Home 1.2.2a.44539 no find bdb*.h

**Comment by nurikk** [comment]
Use z-stack 3.0.1, don't forget to apply .patch from root folder of this project

**Comment by bezonar** [comment]
When trying to compile getting an errors
[Su007]: Unable to open the command file "D:\Zigbee\freepad\CC2530DB\..\..\..\Tools\CC2530DB\f8wEndev.cfg" C:\Users\user\AppData\Local\Temp\EWE91B.tmp 1

**Comment by bezonar** [comment]
It would be great to add a note to readme that project should be placed in folder Z-Stack 3.0.2\Projects\zstack\HomeAutomation\

**Comment by nurikk** [comment]
> It would be great to add a note to readme that project should be placed in folder Z-Stack 3.0.2\Projects\zstack\HomeAutomation\

feel free to raise PR with this changes

**Comment by nurikk** [comment]
https://zigdevwiki.github.io/Begin/IAR_install/
