### ISSUE TITLE
20 single click version

### ISSUE THREAD

**Issue by hqas** [diyruz/freepad#4]
As I am not that familiar with coding, would it be possible to upload the only single click version of the 20 button keypad ?

**Comment by nurikk** [comment]
Kindly check release download version, already has 1/2/3/8/12/20 types

**Comment by hqas** [comment]
Yes i saw them and I am using the 20 type without a problem. But as I dont need multiple clicks I prefer the "ON_OFF_SWITCH_TYPE_MOMENTARY (0) -> no delay, but no multiple clicks, only single" version

**Comment by nurikk** [comment]
then use `mosquitto_pub` to configure your device, readme has examples

**Comment by hqas** [comment]
Ah now I understood how to configure. Thx
