### ISSUE TITLE
Howto compile it? Plz help me :-)

### ISSUE THREAD

**Issue by d0m1n1qu3** [diyruz/freepad#9]
Hi,
i have some ideas and want to play around with this, but i do not understand whit IDE or SDK or VSCode Extensions i have to install.
Can you give me a hint, may be some short lines in which steps i have to do it?

thanks for helping
dominique

EDIT:
until now i download the ZSTACK from TI
extract it and set the ENV ZSTACK_PATH
i copied the Mac config in c_cpp_properties.json to a Linux version and corrected the path

but how i compile it to an hex file ..

**Comment by nurikk** [comment]
Hi, mate! It's no way to compile firmware under Linux. You might need to run VirtualBox with windows to run IAR for 8051.
